version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/default.conf.template:/etc/nginx/templates/default.conf.template
    extra_hosts:
      - "host.docker.internal:host-gateway"
  auth-service:
    build: ./services/auth-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - default_clientSecret=super-secret-secret-that-should-be-regenerated-for-production
      - adac_clientSecret=77871c4bf3e249b3ad9cdcd880ff37c1
      - fusionAuthURL=http://localhost:9011
      - internalFusionAuthURL=http://host.docker.internal:9011
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend-default:
    build:
      context: ./frontend
    ports:
      - "5173:3000"
    environment:
      - VITE_TENANT=default
      - VITE_TENANT_CLIENT_ID=e9fdb985-9173-4e01-9d73-ac2d60d1dc8e
      - VITE_BACKEND_URL=http://localhost/api
  frontend-adac:
    build:
      context: ./frontend
    ports:
      - "5174:3000"
    environment:
      - VITE_TENANT=adac
      - VITE_TENANT_CLIENT_ID=b2cd30ad-bcb9-472b-91d6-effae14db013
      - VITE_BACKEND_URL=http://localhost/api
  pin-service:
    build: ./services/pin-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - internalFusionAuthURL=http://host.docker.internal:9011
    extra_hosts:
      - "host.docker.internal:host-gateway"
  heatmap-service:
    build: ./services/heatmap-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - internalFusionAuthURL=http://host.docker.internal:9011
    extra_hosts:
      - "host.docker.internal:host-gateway"
  analytics-service:
    build: ./services/analytics-service
    ports:
      - "3004:3004"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - internalFusionAuthURL=http://host.docker.internal:9011
    extra_hosts:
      - "host.docker.internal:host-gateway"
  update-service:
    build: ./services/update-service
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - internalFusionAuthURL=http://host.docker.internal:9011
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
