apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: rtwcr1.azurecr.io/services/analytics-service
        ports:
        - containerPort: 3004
      env:
          - name: fusionAuthURL
            valueFrom:
              secretKeyRef:
                name: fusionAuthURL
                key: fusionAuthURL
          - name: internalFusionAuthURL
            valueFrom:
              secretKeyRef:
                name: internalFusionAuthURL
                key: internalFusionAuthURL
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: MONGODB_URI
                key: MONGODB_URI
          - name: BACKEND_URL
            valueFrom:
              secretKeyRef:
                name: BACKEND_URL
                key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3004
    targetPort: 3004
  selector:
    app: analytics-service