apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-adac-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-adac
  template:
    metadata:
      labels:
        app: frontend-adac
    spec:
      containers:
      - name: frontend-adac
        image: rtwcr1.azurecr.io/frontend
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
            name: all_credentials
        env:
          - name: VITE_TENANT
            value: adac
          - name: VITE_TENANT_CLIENT_ID
            value: ddde566b-3b30-4b52-9aed-0016d0deb906
          - name: VITE_TENANT_BACKGROUNDCOLOR
            value: "#FFFF00"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-adac
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2000
    targetPort: 3000
  selector:
    app: frontend-adac