apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-adac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-adac
  template:
    metadata:
      labels:
        app: frontend-adac
    spec:
      containers:
      - name: frontend-adac
        image: rtwcr1.azurecr.io/frontend
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: vitebackendurl
        env:
          - name: VITE_TENANT
            value: adac
          - name: VITE_TENANT_CLIENT_ID
            value: 8038c50d-f338-49c0-8ea3-7bdf2965677e
          - name: VITE_TENANT_LOGO
            value: /adac-logo.png
          - name: VITE_TENANT_BACKGROUNDCOLOR
            value: "#f7d146"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-adac
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4000
    targetPort: 3000
  selector:
    app: frontend-adac