apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rtwcr1.azurecr.io/services/frontend
        ports:
        - containerPort: 5173
        env:
          - name: fusionAuthURL
              valueFrom:
                secretKeyRef:
                  name: fusionAuthURL
                  key: fusionAuthURL
          - name: internalFusionAuthURL
                valueFrom:
                  secretKeyRef:
                    name: internalFusionAuthURL
                    key: internalFusionAuthURL
          - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: MONGODB_URI
                    key: MONGODB_URI
          - name: BACKEND_URL
                valueFrom:
                  secretKeyRef:
                    name: BACKEND_URL
                    key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5173
    targetPort: 5173
  selector:
    app: frontend