apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusionauth
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: fusionauth
  template:
    metadata:
      labels:
        app: fusionauth
    spec:
      containers:
        - name: fusionauth
          image: fusionauth/fusionauth-app
          ports: 
          - containerPort: 9011
          envFrom:
          - secretRef:
              name: posgresqlurl
          - secretRef:
              name: posgresqlrootusername
          - secretRef:
              name: posgresqlrootpassword
          - secretRef:
              name: fusionauthdatabaseusername
          - secretRef:
              name: fusionauthdatabasepassword
          env:
            - name: FUSIONAUTH_APP_RUNTIME_MODE
              value: development
            - name: FUSIONAUTH_APP_MEMORY
              value: 512M
            - name: FUSIONAUTH_APP_URL
              value: http://fusionauth:9011
            - name: SEARCH_TYPE
              value: database
---
apiVersion: v1
kind: Service
metadata:
  name: fusionauth
spec:
  type: LoadBalancer
  selector:
    app: fusionauth
  ports:
    - protocol: TCP
      port: 9011
      targetPort: 9011