name: Create and publish Docker images
on:
  push:
    # branches:
    #   - 'master'
    tags:
      - 'v*'

env:
  REGISTRY: rtwcr1.azurecr.io
  REGISTRY_USERNAME: GitHub-Actions
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        service: [frontend, services/auth-service, services/analytics-service, services/heatmap-service, services/pin-service, services/update-service]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
        
      - name: Extract metadata (tags, labels) for Docker (${{ matrix.service }})
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.service }}

      - name: Build and push Docker image (${{ matrix.service }})
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}